FROM judge0/api:1.4.0

ARG DEV_USER=judge0
ARG DEV_USER_ID=1000

RUN apt-get update && \
    apt-get install -y --no-install-recommends vim && \
    useradd -u $DEV_USER_ID -m -r $DEV_USER && \
    echo "$DEV_USER ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers

USER $DEV_USER

RUN sudo apt-get install -y cython lp-solve liblpsolve55-dev python-pip
RUN git clone "https://github.com/iradicek/clara" /tmp/clara && cd /tmp/clara && sudo make install

ENV LD_LIBRARY_PATH=/usr/lib/lp_solve/

CMD ["sleep", "infinity"]

LABEL maintainer="Herman Zvonimir Došilović, hermanz.dosilovic@gmail.com"
